<article id="news" class="detail">

<h2><?php echo $this->escape($this->object->headline); ?></h2>
<p class="minor small">
    <?php echo strftime('%e. %B %Y', $this->object->getPublish('U')); ?> |
    <?php echo $this->escape($this->object->user->title); ?>
    <?php echo $this->escape($this->object->user->firstname); ?>
    <?php echo $this->escape($this->object->user->lastname); ?>
</p>

<?php if ($this->object->image) { ?>
    <img
        alt="<?php echo $this->object->image->name; ?>"
        src="/thumb_<?php echo $this->object->image->id; ?>_ffp_200x150.jpg"
    />
<?php } ?>

<?php echo $this->markdown($this->escape($this->object->content)); ?>

<p class="minor small">Tags: <?php echo $this->escape(implode(', ', $this->object->tags->toArray())); ?></p>

<?php echo $this->partial('partial/addthis.phtml'); ?>

<h2>Kommentare</h2>
<ul class="comments">
    <?php echo $this->partialLoop('partial/comment.phtml', $this->object->comments); ?>
</ul>

<h2>Schreiben Sie einen Kommentar</h2>
<?php echo $this->form; ?>

</article>
