<section id="news" class="overview">
    <?php
        foreach ($this->paginator as $news)
        {
            echo $this->partial(
                'partial/news.phtml',
                array (
                    'item'  => $news
                )
            );
        }

        echo $this->paginationControl(
                $this->paginator,
                'Sliding',
                'partial/pagination.phtml'
        );
    ?>
</section>
