<article id="lecturer" class="detail">
    <h2>
        <?php echo $this->escape($this->object->title); ?>
        <?php echo $this->escape($this->object->firstname); ?>
        <?php echo $this->escape($this->object->lastname); ?>
    </h2>
    <p class="minor small">
        <?php echo strftime('%e. %B %Y', $this->object->getPublish('U')); ?> |
        <?php echo $this->escape($this->object->user->title); ?>
        <?php echo $this->escape($this->object->user->firstname); ?>
        <?php echo $this->escape($this->object->user->lastname); ?>
    </p>

    <div>
        <?php if ($this->object->image) { ?>
            <img
                alt="Foto von <?php echo $this->escape($this->object->title) . ' ' . $this->escape($this->object->firstname) . ' ' . $this->escape($this->object->lastname); ?>"
                src="/thumb_<?php echo $this->object->image->id; ?>_ffp_90x120.jpg"
            />
        <?php } ?>

        <?php if (!empty ($this->object->email)) { ?>
            <p><?php echo $this->escape($this->object->email); ?></p>
        <?php } ?>

        <?php if (!empty ($this->object->website)) { ?>
            <p><?php echo $this->escape($this->object->website); ?></p>
        <?php } ?>

        <p><?php echo $this->escape($this->object->subject); ?></p>
    </div>

    <?php echo $this->markdown($this->escape($this->object->content)); ?>

    <?php
        if (!empty ($this->object->interview))
        {
            echo $this->markdown($this->escape($this->object->interview));
        }
    ?>

    <?php echo $this->partial('partial/addthis.phtml'); ?>
</article>
