<section id="events" class="overview">
    <?php
        foreach ($this->paginator as $event)
        {
            echo $this->partial(
                'partial/event.phtml',
                array (
                    'item'  => $event
                )
            );
        }

        echo $this->paginationControl(
                $this->paginator,
                'Sliding',
                'partial/pagination.phtml'
        );
    ?>
</section>
