<tr>
    <td><?php echo $this->escape($this->object->headline); ?></td>
    <td>
        <?php echo $this->escape($this->object->user->title); ?>
        <?php echo $this->escape($this->object->user->firstname); ?>
        <?php echo $this->escape($this->object->user->lastname); ?>
    </td>
    <td><?php echo $this->object->publish; ?></td>
    <td>
        <ul>
            <li>
                <a
                    href="/admin/news/comment/<?php echo $this->object->id; ?>"
                >Kommentare</a>
            </li>
            <li>
                <a
                    href="/news/<?php echo $this->object->url; ?>"
                >Vorschau</a>
            </li>
            <li>
                <a
                    href="/admin/news/edit/<?php echo $this->object->id; ?>"
                >Bearbeiten</a>
            </li>
            <li>
                <a
                    class="confirm"
                    href="/admin/news/delete/<?php echo $this->object->id; ?>"
                >Löschen</a>
            </li>
        </ul>
    </td>
</tr>
